server:
  port: 9000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


  jpa:
    show-sql: true
